#
#Fri Mar 13 15:23:22 UYT 2026
acceptInsecureCerts=true
browserName=chrome
goog\:chromeOptions={args\=[test-type, no-sandbox, ignore-certificate-errors, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, disable-dev-shm-usage, disable-extensions, headless, test-type, no-sandbox, ignore-certificate-errors, incognito, disable-infobars, disable-gpu, disable-default-apps, disable-popup-blocking, disable-dev-shm-usage, disable-extensions, headless, --headless, remote-allow-origins\=*], binary\=/usr/bin/chromium, extensions\=[]}
